(function(c){function s(b){if(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))return unescape(b[2]||"");return""}function t(b){b=b||document.domain;b.indexOf("www.")===0&&(b=b.substr(4));var a=b.match(/([a-z0-9][a-z0-9\-]*?\.(?:com|cn|net|org|gov|info|la|cc|co|jp)(?:\.(?:cn|jp))?)$/);if(a)return a[0];return b}function C(){var b,a;a=navigator;if(a.plugins&&a.mimeTypes.length){if((b=a.plugins["Shockwave Flash"])&&b.description)return b.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,
".")}else if(a.userAgent&&a.userAgent.indexOf("Windows CE")>=0){a=3;for(b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1)),a++}catch(d){break}return a.toString()}else if(j()){try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(c){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a=6,b.AllowScriptAccess="always"}catch(g){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash,ShockwaveFlash")}catch(e){}}if(b)return b.GetVariable("$version").split(" ")[1].replace(/,/g,
".")}return"0"}function D(){var b=document.referrer,a=b.replace(/^http:\/\//,""),d=a.indexOf("/");d!=-1&&(a=a.substr(0,d));a=a.replace(/:\d+$/,"");a=t(a);d=t();var f=s("BAIDU_CLB_REFER");if(d==a&&f!="")return c.encodeURIComponent?encodeURIComponent(f):escape(f);else if(d!=a)return document.cookie="BAIDU_CLB_REFER="+escape(b)+""+(d?";domain="+escape(d):"")+"",c.encodeURIComponent?encodeURIComponent(b):escape(b);return""}function u(b,a){var d="di="+b+(a?"&fn="+a:"")+"&tm=BAIDU_CLB_SETJSONADSLOT&mod_t="+
(new Date(document.lastModified)).getTime()+"&visi_t="+(new Date).getTime()+"&flash_v="+C()+"&java="+(navigator.javaEnabled()?1:0)+"&new=1";c.screen&&(d+="&screen_h="+c.screen.height+"&screen_w="+c.screen.width+"&page_h="+c.screen.availHeight+"&page_w="+c.screen.availWidth+"&color="+c.screen.colorDepth);var f="&asp_refer="+D()+"&asp_url="+(c.encodeURIComponent?encodeURIComponent(document.URL):escape(document.URL))+"&b_lang=",g=navigator;d+=f+(g.language||g.browserLanguage)+"&baidu_id="+s("BAIDUID");
return E+"?"+d}function k(b){return"baidu_clb_slot_"+b}function F(b){c.BAIDU_DAN_readySlotId=b;document.write('<script src="'+G+'"><\/script>')}function H(b,a){var d;a:{var f=a._html.split("|");d=0;for(var g=f.length;d<g;d++){var e=f[d].split("=");if(e[0]=="cpro_template"){if(e[1].split("_")[1].indexOf("xuanfu")==0){d=!0;break a}break}}d=!1}f=d?I:J;(d=c[d?"BAIDU_CLB_CPROFSLOT":"BAIDU_CLB_CPROCSLOT"])?d(b,a):(c.tempClbCproAdObj=a,c.tempClbCproAdSlotId=b,document.write('<script type="text/javascript" src="'+
f+'"><\/script>'))}function K(b,a){var c=a._html,f=a._w,g=a._h,e=k(b);if(c||a._fxp)c&&a._isMlt?document.write(c):j()?(document.write('<div id="'+e+'"></div>'),v(b,e,f,g,a._html)):(document.write('<div id="'+e+'"></div>'),w(b,e,f,g,a._html))}function L(b,a){function d(){j()?M(b,a):N(b,a);var d=a._st;d>0&&c.setTimeout(function(){var a=document.getElementById(k(b));a&&a.parentNode.removeChild(a)},d*1E3)}function f(){var c=a,e=document.getElementById(k(b));if(e){e=e.style;var d=c._vs,f=c._hs,l=m(),i=
document,h=l?document.body:document.documentElement,q=i.documentElement.scrollTop||i.body.scrollTop;i=i.documentElement.scrollLeft||i.body.scrollLeft;if(j()&&(n()<7||l))if(c._sf)c._top==1?e.top=q+f+"px":n()<7?e.top=q+h.clientHeight-f-c._h-17+"px":e.bottom=f-q+"px",c._left==1?e.left=i+d+"px":e.right=d-i+"px";else if(c._top!=1)e.top=h.clientHeight-f-c._h-17+"px"}}a._html!=""&&(c.attachEvent?(c.attachEvent("onload",d),c.attachEvent("onresize",f),(n()<7||m())&&c.attachEvent("onscroll",f)):c.addEventListener&&
(c.addEventListener("load",d,!1),c.addEventListener("resize",f,!1)))}function O(b,a){var d=a._h,f=a._w,g=0,e=0,p=a._html,h,l,i="newwindow"+b,k="about:blank";if(p!="")if(j()&&document.domain!=c.location.hostname&&(k="javascript:void( (function(){var d=document;d.open();"+x()+"d.write('');d.close();})() )"),a._top==1?g=a._hs:c.screen&&(g=c.screen.availHeight-a._hs-d),a._left==1?e=a._vs:c.screen&&(e=c.screen.availWidth-a._vs-f),l="height="+d+",width="+f+",top="+g+",left="+e+",screenX="+g+",screenY="+
e+",toolbar=no,menubar=no,scrollbars=no,resizable=no,location=no,status=no",a._bf||!j()){if(h=c.open(k,i,l))d=h.document,d.open("text/html","replace"),d.write(p),d.close(),a._st>0&&c.setTimeout(function(){h&&h.close()},a._st*1E3)}else c.attachEvent&&c.attachEvent("onunload",function(){var a=c.event;if(a.clientY<0&&!a.ctrlKey||a.altKey)if(a=c.open(k,i,l)){var b=a.document;b.open("text/html","replace");b.write(p);a.focus()}})}function M(b,a){var d=k(b);a=c[h][b];var f="absolute",g=document.createElement("div");
a._sf&&n()>6&&!m()&&(f="fixed");g.id=d;g.style.position=f;y(g,a);g.innerHTML=z();document.body.appendChild(g);v(b,d,a._w,a._h,a._html)}function N(b,a){var d=k(b);a=c[h][b];var f=document.getElementById(d);if(!f)f=document.createElement("div"),f.id=d;f.innerHTML=z();f.style.position=a._sf?"fixed":"absolute";y(f,a);document.body.appendChild(f);w(b,d,a._w,a._h,a._html)}function y(b,a){var c=b.style;c[a._left==1?"left":"right"]=a._vs+"px";c[a._top==1?"top":"bottom"]=a._hs+"px";c.width=a._w+"px";c.height=
a._h-0+17+"px";c.border="0";c.zIndex="2147483647"}function w(b,a,d,f,g){b="baidu_clb_slot_iframe_"+b;a=document.getElementById(a);var e=document.createElement("iframe");e.id=b;e.name=b;e.width=d;e.height=f;e.vspace=0;e.hspace=0;e.allowTransparency="true";e.scrolling="no";e.marginWidth=0;e.marginHeight=0;e.frameBorder=0;e.style.border=0;e.style.display="block";a.insertBefore(e,a.firstChild);var h=e.contentWindow.document;h.write(g);c.setTimeout(function(){h.close()},0)}function v(b,a,c,f){var g="baidu_clb_slot_iframe_"+
b;a=document.getElementById(a);var e=document.createElement("iframe");e.id=g;e.name=g;e.width=c;e.height=f;e.vspace=0;e.hspace=0;e.allowTransparency="true";e.scrolling="no";e.marginWidth=0;e.marginHeight=0;e.frameBorder=0;e.style.border=0;e.style.display="block";a.insertBefore(e,a.firstChild);e.contentWindow.location="javascript:void((function(){var d=document;d.open('text/html', 'replace');"+x()+"d.write(parent."+h+"['"+b+"']._html);d.close()})())"}function z(){return'<div style="height:'+(j()&&
m()?"17":"15")+"px;border:1px solid #E1E1E1;background:#F0F0F0;padding:0;margin:0;"+(j()?"overflow:hidden;":"")+'"><div style="float:right;clear:right;margin:2px 5px 0 0;width:39px;height:15px;cursor:pointer;background:transparent url(\''+P+"') no-repeat scroll 0 0;"+(j()?"_display:inline;":"")+'" onmouseover="this.style.backgroundPosition=\'0 -20px\';" onmouseout="this.style.backgroundPosition=\'0 0\';" onclick="this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode);"></div></div>'}
function x(){if(document.domain!=c.location.hostname)return"document.domain='"+document.domain+"';";return""}function j(){return/msie/i.test(navigator.userAgent)&&!c.opera}function n(){var b=navigator.userAgent,a=b.indexOf("MSIE ");return a==-1?0:parseFloat(b.substring(a+5,b.indexOf(";",a)))}function m(){return document.compatMode=="CSS1Compat"?!1:!0}function A(b){var a,d,f,g;for(d in b)f=b[d],typeof f!="function"&&(a=d,g=f);c[h][a]=g;g[B]=!0;if(g._isMlt==2)b=H;else if(g._isMlt==3)b=F;else switch(g._stype){case 0:case 3:b=
K;break;case 1:b=L;break;default:b=O}b(a,g)}if(/msie/i.test(navigator.userAgent)&&!c.opera&&c.addEventListener&&!c.BAIDU_CLB_IE9Fixed){c.BAIDU_CLB_IE9Fixed=!0;var r=document.getElementsByTagName("head")[0],o=r.getElementsByTagName("base")[0];if(o){var Q=o.nextSibling;c.addEventListener("DOMContentLoaded",function(){r.insertBefore(o,Q)},!1);r.removeChild(o)}}var h="BAIDU_CLB_SLOTS_MAP";c[h]||(c[h]={});var B="__BAIDU_CLB_DONE__";c.BAIDU_CLB_SLOTS_MANAGER||(c.BAIDU_CLB_SLOTS_MANAGER={_container:{},register:function(b){this._container[b]=
1},tryAddSlot:function(b,a){if(this._container[a]===1)return b[b.length]=a,!0},setLoaded:function(b){this._container[b]&&(this._container[b]=2)},setUnloaded:function(b){this._container[b]&&(this._container[b]=1)}});c.BAIDU_CLB_addSlot=function(b){c.BAIDU_CLB_SLOTS_MANAGER.register(b)};c.BAIDU_CLB_enableAllSlots=new Function;var E="http://cb.baidu.com/ecom",P="http://drmcmm.baidu.com/js/img/close.gif",J="http://cpro.baidu.com/cpro/ui/cc.js",I="http://cpro.baidu.com/cpro/ui/cf.js",G="http://cbjs.baidu.com/js/dn.js";
c.BAIDU_CLB_SETJSONADSLOT=A;c.BAIDU_CLB_ADDAD=function(b){for(var a in b)b.hasOwnProperty(a)&&(c.BAIDU_CLB_SLOTS_MAP[a]=b)};c.BAIDU_CLB_preloadSlots=function(){function b(a){for(var b=[],c=[],d=a.length,f=0;f<d;f++)b[f]="BAIDU_CLB_ADDAD",c[f]="BAIDU_CLB_SETJSONADSLOT";a=u(a[0],b[0]).replace("di="+a[0],"di="+a.join(",")).replace("fn="+b[0],"fn="+b.join(",")).replace("tm=BAIDU_CLB_SETJSONADSLOT","tm="+c.join(","));document.write('<script type="text/javascript" charset="utf-8" src="'+a+'"><\/script>')}
for(var a=c.BAIDU_CLB_SLOTS_MANAGER,d=arguments.length,f=0,g=[];f<d;f++)a.tryAddSlot(g,arguments[f])&&a.setLoaded(g[g.length-1]),g.length>=16&&(b(g),g=[]);g.length&&b(g)};c.BAIDU_CLB_fillSlot=c.BAIDU_CLB_singleFillSlot=function(b){var a=c.BAIDU_CLB_SLOTS_MAP[b];a&&!a[B]?A(a):c[h][b]||document.write('<script type="text/javascript" charset="utf-8" src="'+u(b,"BAIDU_CLB_SETJSONADSLOT")+'"><\/script>')};c.BAIDU_CLB_SETHTMLSLOT=new Function})(window);
